CREATE DATABASE tpinstasql;

USE tpinstasql;

CREATE TABLE users(
  id INT AUTO_INCREMENT PRIMARY KEY,
  last_name VARCHAR(50) NOT NULL,
  first_name VARCHAR(50) NOT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(50) NOT NULL UNIQUE,
  avatar VARCHAR(100) NOT NULL
);

CREATE TABLE photos(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  image_url VARCHAR(100) NOT NULL,
  user_id INT,
  FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE likes(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  user_id INT,
  photo_id INT NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY(photo_id) REFERENCES photos(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE comments(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  user_id INT,
  photo_id INT NOT NULL,
  content VARCHAR(100),
  FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY(photo_id) REFERENCES photos(id) ON UPDATE CASCADE ON DELETE CASCADE
);